pipeline:
  build:
    image: ruby:${RUBY_VERSION}
    commands:
      - ruby -v
      - gem --version
      - bundle install
      - ./script/ci

matrix:
  RUBY_VERSION:
    - 2.3.6
    - 2.4.2
    - 2.5.0
