pipeline:
  restore-cache:
    image: plugins/s3-cache:1
    pull: true
    endpoint: http://minio.company.com
    secrets: [ s3_cache_access_key, s3_cache_secret_key ]
    restore: true

  rubocop:
    image: ruby:latest
    commands:
      - ./script/ci qa

  specs_mri_23:
    group: build
    image: ruby:2.3.6
    commands:
      - ./script/ci

  specs_mri_24:
    group: build
    image: ruby:2.4.2
    commands:
      - ./script/ci

  specs_mri_25:
    group: build
    image: ruby:2.5.0
    commands:
      - ./script/ci

  specs_jruby_91:
    group: build
    image: jruby:9.1.15.0
    commands:
      - ./script/ci

   rebuild-cache:
    image: plugins/s3-cache:1
    pull: true
    endpoint: http://minio.company.com
    access_key: myaccesskey
    secret_key: supersecretKey
    rebuild: true
    mount:
      - node_modules
    when:
      event: push

  flush_cache:
    image: plugins/s3-cache:1
    pull: true
    endpoint: http://minio.company.com
    access_key: myaccesskey
    secret_key: supersecretKey
    flush: true
    flush_age: 14
